version: '3.6'

services:
  flume:
    build: 
      context: .
    image: bamcis/flume-alpine:1.8.0
    env_file:
    - ./flume.env
    container_name: flume
    ports:
    - 44444:44444
    - 41414:41414
    networks:
    - default